remove second dockerfile
ONSdigital/ras-secure-message pull request #421
Opened 2024-07-24 13:59 UTC by anwilkie

# What and why?
Removing the dockerfile in the root directory to ensure consistency with other repos.

# How to test?
Check GA build

# Jira
[Card](https://jira.ons.gov.uk/browse/RAS-313)

2024-07-24 15:33 UTC, anwilkie commented
/deploy wilkia

2024-07-29 11:14 UTC, arroyoAle approved these changes
Works fine just a little comment

2024-07-29 11:14 UTC, arroyoAle commented on Makefile
> +	pipenv check -i 70612 -i 71064 -i 70624
again there is an update for requests (71064) can be a separate card

2024-07-30 14:24 UTC, matthew-robinson-ons commented on Pipfile
> +urllib3 = "*"
we shouldn't be importing urllib3 it is managed as a subdependency of a number of packages, e.g. requests

2024-07-30 14:25 UTC, matthew-robinson-ons requested changes
Just the one comment around urlib, the vulnerability is now fixed on main so after merging the import can be removed

2024-08-01 14:46 UTC, closed without merging